import { Outfit } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import Header from "@/components/header";
import { ClerkProvider } from "@clerk/nextjs";
import { dark } from '@clerk/themes'

const outfit = Outfit({ subsets: ["latin"]});

export const metadata = {
  title: "Sensai - AI Career Coach",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider
      appearance={{
        baseTheme: dark,
      }}
    >

    <html lang="en" suppressHydrationWarning>
      <body
        className={`${outfit.className}`}
        >
        <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
            >
            <Header />
            <main className="min-h-screen">{children}</main>
            <footer className="bg-background py-12">
              <div className="container mx-auto text-center text-gray-200"> 
                <p>Made by Harsh Dobariya</p>
              </div>
            </footer>
        </ThemeProvider>
      </body>
    </html>
    </ClerkProvider>
  );
}
